export const firebaseConfig = {
  apiKey: "AIzaSyA35D1SwQdAPOAp-wxRYsezWQI7rvIPQAY",
  authDomain: "counting-system.firebaseapp.com",
  projectId: "counting-system",
  storageBucket: "counting-system.appspot.com",
  messagingSenderId: "726733968843",
  appId: "1:726733968843:web:d68da6c09a4a1aac7fd24e",
};

//firabase base path
export const BASE_PATH = 'incinema-' 

//firebase list of items
export const arr = [
    "AGUILAR",
    "ALITAYA",
    "ANGIO",
    "AWAY",
    "BAAY EXT",
    "BACABAC",
    "BALOCOC",
    "BALOLING",
    "BANAYBAYAN EXT",
    "BATENG",
    "BINDAY",
    "BINMALEY",
    "BISBISOCOL",
    "BOLO",
    "BONUAN",
    "BUGALLON",
    "CALASIAO",
    "CALIT",
    "CALMAY",
    "CARAEL",
    "COLISAO",
    "DAGUPAN CITY",
    "DAVID",
    "DOMALANDAN",
    "DULAG",
    "GARCIA",
    "HACIENDA",
    "HAWAY",
    "INMALOG",
    "LAGUIT CENTRO",
    "LEET",
    "LINGAYEN",
    "LOBONG",
    "LONGOS CALASIAO EXT",
    "LONGOS SAN FABIAN EXT",
    "LUYAN",
    "MAAMBAL",
    "MAASIN EXT",
    "MABILAO",
    "MAGTAKING",
    "MALINDONG EXT",
    "MAMALINGLING",
    "MANAOAG",
    "MANAOAG DOS",
    "MANGALDAN",
    "MAPANDAN",
    "MATALAVA",
    "NIÑOY",
    "PANGAPISAN NORTH",
    "PALUA EXT",
    "PUGARO",
    "QUETEGAN",
    "ROSARIO",
    "SALOMAGUE",
    "SAN FABIAN",
    "SAN JACINTO",
    "SAN RAMON EXT",
    "TALIBAEW EXT",
    "TULONG"
        ] ;
